### ISSUE TITLE
Permisos incorrectos

### ISSUE THREAD

**Issue by Wasberth** [Ricardo8421/crujirepo#7]
Hay que validar TODOS los archivos php para que se valide el acceso que tiene cada usuario

También hay que validar que una vez que el profesor contestó la encuesta, no pueda acceder ingresando la url

**Comment by Wasberth** [comment]
Esto también incluye que los profesores que tengan el acceso congelado no puedan acceder, para esto faltaría una página que diga que no tiene permiso

**Comment by JoseLuisMonroy** [comment]
El primer problema ha sido corregido en el commit https://github.com/Ricardo8421/crujirepo/commit/57ae9c5223cfcf4256527ab3f32ab20818c23014

**Comment by JoseLuisMonroy** [comment]
Problema corregido en su totalidad en el commit  https://github.com/Ricardo8421/crujirepo/commit/cc5e19f41e88b3208a50f4b9f827a0385fb09ddb
