### ISSUE TITLE
JSON muy largo en pdf

### ISSUE THREAD

**Issue by Wasberth** [Ricardo8421/crujirepo#9]
Cuando muchos profesores contestan la encuesta, el sistema manda error al intentar generar el pdf

**Comment by JoseLuisMonroy** [comment]
Bug reparado, para checar modificaciones, checar el commit https://github.com/Ricardo8421/crujirepo/commit/dd0fc3d1148311b1db8e246b34a5bcb93806073e

**Comment by Wasberth** [comment]
Los pdfs de academias que tienen nombres con acentos siguen sin funcionar correctamente

**Comment by JoseLuisMonroy** [comment]
Corregido en https://github.com/Ricardo8421/crujirepo/commit/b179090d5d0c7f4a0e56133c4a2335dc3b47d15e
